### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by manjotsidhu** [manjotsidhu/3D_modelling#3]
This is the TODO list that we need to complete ASAP : -

- [x] Making Compressor model on blender.
- [x] Exporting compressor model to GLTF.
- [x] Importing model and necessary movement controls in three.js.
- [x] Making each and every object gradient properties with proper orientation.
- [x] Feature 1: Show annotations on vertex on-click.
- [x] Feature #2: Each individual part/component selection.
- [x] Realtime gradient values from cloud
